### ISSUE TITLE
ModuleNotFoundError: No module named 'Keccak'

### ISSUE THREAD

**Issue by nyxynyx** [kumrzz/pymonerotools#1]
After installing `pymonerotools`

    pip install https://github.com/kumrzz/pymonerotools/zipball/master

and running a file with just the import line

    import pymonerotools

I am getting the error

	Traceback (most recent call last):
	  File "test.py", line 1, in <module>
	    import pymonerotools
	  File "C:\Users\y\Anaconda2\envs\test\lib\site-packages\pymonerotools\__init__.py", line 1, in <module>
	    from pymonerotools.toolz import *
	  File "C:\Users\y\Anaconda2\envs\test\lib\site-packages\pymonerotools\toolz.py", line 10, in <module>
	    import Keccak, ed25519#in this library
	ModuleNotFoundError: No module named 'Keccak'

Any ideas? 

I am running `Python 3.6.2 :: Continuum Analytics, Inc.` on Windows 10 x64

**Comment by nyxynyx** [comment]
Manually copied the 2 files `Keccak.py` and `ed25519.py` to the current working directory and reran the script with a single import statement.

Now getting the new error:

    Traceback (most recent call last):
      File "test.py", line 1, in <module>
        import pymonerotools
      File "C:\Users\y\Anaconda2\envs\test\lib\site-packages\pymonerotools\__init__.py", line 1, in <module>
        from pymonerotools.toolz import *
      File "C:\Users\y\Anaconda2\envs\test\lib\site-packages\pymonerotools\toolz.py", line 10, in <module>
        import Keccak, ed25519#in this library
      File "C:\Users\y\Desktop\Code\test\wallet\xmr\ed25519.py", line 27, in <module>
        d = -121665 * inv(121666)
      File "C:\Users\y\Desktop\Code\test\wallet\xmr\ed25519.py", line 25, in inv
        return expmod(x,q-2,q)
      File "C:\Users\y\Desktop\Code\test\wallet\xmr\ed25519.py", line 20, in expmod
        t = expmod(b,e/2,m)**2 % m
      File "C:\Users\y\Desktop\Code\test\wallet\xmr\ed25519.py", line 20, in expmod
        t = expmod(b,e/2,m)**2 % m
      File "C:\Users\y\Desktop\Code\test\wallet\xmr\ed25519.py", line 20, in expmod
        t = expmod(b,e/2,m)**2 % m
      [Previous line repeated 972 more times]
      File "C:\Users\y\Desktop\Code\test\wallet\xmr\ed25519.py", line 19, in expmod
        if e == 0: return 1
    RecursionError: maximum recursion depth exceeded in comparison
